---
server:
  port: 8888    
        
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mimaraslan/spring-cloud-config1 # default 
          search-paths:
            - 'station*'  
          force-pull: true  
          repos:
             local:
                pattern: '*/config2'
                uri: https://github.com/mimaraslan/spring-cloud-config2 # alternative
                search-paths:
                 - 'station*'  
  profiles:
    active:
    - dev,prod